repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args: [--py3-plus]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^.+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.5.0
          - pydocstyle==5.0.2
        files: ^.+\.py$
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=tests/bandit.yaml
        files: ^.+\.py$
        exclude: ^[^/]+\.py$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        files: ^.+\.json$
      - id: trailing-whitespace
      # Uncomment lines below if you want to follow classical GitHub flow style development
#      - id: no-commit-to-branch
#        args:
#          - --branch=main
  - repo: local
    hooks:
      # Run mypy through our wrapper script in order to get the possible
      # pyenv and/or virtualenv activated; it may not have been e.g. if
      # committing from a GUI tool that was not launched from an activated
      # shell.
      - id: mypy
        name: mypy
        entry: bin/run-in-env mypy
        language: script
        types: [python]
        require_serial: true
        files: ^.+\.py$
      - id: pylint
        name: pylint
        entry: bin/run-in-env python3 -m pylint
        language: system
        types: [python]
        files: ^.+\.py$
      - id: pytest
        name: pytest
        entry: bin/run-in-env pytest
        language: system
        pass_filenames: false
        always_run: true
